spring:
  application:
    name: individuals_api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/my-app-realm

keycloak:
  auth-server-url: http://localhost:9090
  realm: my-app-realm
  client-id: my-app-client
  client-secret: pYeKYYS6Yp1YziNjgDjQPHgtu7RbwPog
  admin:
    username: my_user_manager
    password: my_user_manager_password

server:
  port: 8091